### PR TITLE
CORE-1540: fixed a few potential panic conditions caused by type asse…

### PR DESCRIPTION
**Pull request by slr71**
…rtions

There's a problem with request format inconsistency that's causing this, but it would be good to remove any type assertions for data extracted from the request body. This change also adds a little flexibility by making it easy to search multiple field names for a single piece of data.

### CODE REVIEW

**Review by ianmcorvidae — APPROVED** [review]
Looks reasonable to me. I guess probably it's worth fixing the one unchecked error that golangci-lint found, but the change looks fine.

**Review by sri2k1us — APPROVED** [review]
:shipit:

**Comment by slr71** [comment]
> Looks reasonable to me. I guess probably it's worth fixing the one unchecked error that golangci-lint found, but the change looks fine.

Ah, yes I'd forgotten to add an error check when I removed one of the type assertions. Thanks for mentioning that

**Comment by slr71** [comment]
Thanks for the reviews!

**Pull request merged**
